### ISSUE TITLE
neumo - Address limit can be bypassed using a contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-07-beam-auction-judging#61]
neumo

high

# Address limit can be bypassed using a contract

## Summary
The auction contract is designed to disallow users from minting more than `CAP_PER_ADDRESS` NFTs per acount. This can easily be bypassed using a smart contract.

## Vulnerability Detail
As we have seen in the past, this kind of protection to prevent a single person to own a big amount of assets simply don't work. The Adidas NFT of December 2021 is a good example, where there was a cap of 2 NFTs per account, the sale lasted just 10 seconds, and a single user was able to mint 330 NFTs:
https://nftevening.com/someone-sidestepped-adidas-nft-minting-terms-to-score-330-nfts/

The idea to bypass the limit in a single transaction is to use a smart contract that executes a loop, inside of which it deploys a simple contract that mints `CAP_PER_ADDRESS` NFTs in the `MeritDutchAuction` contract and sends them to the attacker. The limit here is just the gas, the attacker will have to make the loop short enough to not surpass the block gas limit.

## Impact
High.

## Code Snippet
https://github.com/sherlock-audit/2023-07-beam-auction/blob/main/dutch-nft/src/MeritDutchAuction.sol#L156-L159

## Tool used
Manual review.

## Recommendation
Add this constraint to the `mint` function:

```solidity
require(tx.origin == msg.sender)
```

This will ensure that the caller is an EOA and not a smart contract.

Duplicate of #59

**Comment by neumoxx** [comment]
Escalate
The `MeritDutchAuction` contract clearly sets a maximum cap per address, the intention of which is unclear because of the lack of documentation, but we can assume it may be to avoid that a single user mints an arbitrary amount of NFTs with the intention of selling them in secondary markets and make a profit (otherwise I don't see why would it be capped). This is what happened in the example above (Adidas), where there was a huge FOMO and the high demand for the NFT made the sale end very quickly (10 seconds) and the only feasible way to buy a big amount of NFTs was using a smart contract. If this happened it would hurt the protocol and its users because it would be unfair that regular users (i.e: non-developers) could only mint 4 NFTs in a single transaction while users able to deploy a contract for this purpose could mint an arbitrary amount. Also, if the auction ends with all items sold quickly, users that were not able to buy would be forced to buy at a higher price in a marketplace (in case they still want an NFT from the auction).

The only difference with the Adidas example is that in this case we are dealing with a Dutch auction, and in the other case it was a regular sale with a fixed price per NFT. This difference does not affect the fact that a user can still mint an arbitrary number of items, only he would have to monitor the number of items left and the mempool to be able to mint the desired number when the price is low enough.

**Comment by sherlock-admin2** [comment]
> Escalate
> The `MeritDutchAuction` contract clearly sets a maximum cap per address, the intention of which is unclear because of the lack of documentation, but we can assume it may be to avoid that a single user mints an arbitrary amount of NFTs with the intention of selling them in secondary markets and make a profit (otherwise I don't see why would it be capped). This is what happened in the example above (Adidas), where there was a huge FOMO and the high demand for the NFT made the sale end very quickly (10 seconds) and the only feasible way to buy a big amount of NFTs was using a smart contract. If this happened it would hurt the protocol and its users because it would be unfair that regular users (i.e: non-developers) could only mint 4 NFTs in a single transaction while users able to deploy a contract for this purpose could mint an arbitrary amount. Also, if the auction ends with all items sold quickly, users that were not able to buy would be forced to buy at a higher price in a marketplace (in case they still want an NFT from the auction).
> 
> The only difference with the Adidas example is that in this case we are dealing with a Dutch auction, and in the other case it was a regular sale with a fixed price per NFT. This difference does not affect the fact that a user can still mint an arbitrary number of items, only he would have to monitor the number of items left and the mempool to be able to mint the desired number when the price is low enough.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Oot2k** [comment]
Other issue of the same Family was escalated, please see my comment there:
https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/19#issuecomment-1651888754

**Comment by neumoxx** [comment]
Thanks @Oot2k , absolutely agree with @eugenioclrc 's escalation.

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #59 
https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/19#issuecomment-1653662281

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [neumoxx](https://github.com/sherlock-audit/2023-07-beam-auction-judging/issues/61/#issuecomment-1651517808): rejected
